apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitops-app
  name: gitops-app-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitops-app
    spec:
      containers:
      - image: 681294981804.dkr.ecr.ap-southeast-2.amazonaws.com/gitops-app:latest
        imagePullPolicy: Always
        name: gitops-app
        ports:
        - containerPort: 80